name: Crawl Zalo FAST

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # ⚡ fix puppeteer crash
      - name: Install Chromium deps
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install Puppeteer core (NHẸ + NHANH)
        run: npm install puppeteer-core

      - name: Run Crawl
        run: node crawl.js

      - name: Commit JSON
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add products.json
          git commit -m "update" || echo "no change"
          git push
